name: release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.6.linux-amd64.tar.gz"
        ldflags: "-w -s -X 'github.com/Sora233/buntdb-cli/main.COMMIT=${{ github.sha }}' -X 'github.com/Sora233/buntdb-cli/main.GOVERSION=go1.15.6.linux-amd64'"
